### ISSUE TITLE
Include setup guide

### ISSUE THREAD

**Issue by shakarganjaa** [ruky-a/freelance#11]
Hello,
Hope you are doing great. I was searching for something similar and found this repo, must say that it looks to good and I've also checked the demo app. It looks great!

however, I was wondering if you could add a 'how-to" or setup guide in the readme? That would basically tell us how to run and practice this on local machine after cloning it? I hope you understand. 

I'm not even sure if you intended to keep this repo as open source or not. 

Thank you !

**Comment by ruky-a** [comment]
Hi,

Thanks for reaching out and I'm glad you appreciate my work. I will set up
a guide in readme as suggested in the next few days.

Regards,
Rukevwe
